# /action.yml
name: 'docker-actions-runner'
description: ''
runs:
  using: "composite"
  steps: 
    - shell: sh
      run: |
        #!/bin/bash
        repo=runner-$(basename ${{ inputs.repo }} /)
        docker image rm -f $repo || true
        $(docker build . -t $repo && docker run --name $repo $repo) &
inputs:
  repo:
    required: true
  