# /action.yml
name: 'docker-actions-runner'
description: ''
runs:
  using: "composite"
  steps: 
    - shell: sh
      run: |
        #!/bin/bash
        repo=$(basename ${{ inputs.repo }} /)
        $(docker rmi $repo && docker build . -t $repo && docker run $repo --name $repo) &
inputs:
  repo:
    required: true
  